In [24]:
import pandas as pd
import glob
import os

def load_all_pkl(folder):
    pkl_paths = glob.glob(os.path.join(folder, "*.df"))
    print(len(pkl_paths))
    list_of_dfs = []
    for path in pkl_paths:
        try:
            df = pd.read_pickle(path)
        except:
            continue
        list_of_dfs.append(df)
    return pd.concat(list_of_dfs)

In [25]:
#bigdf = load_all_pkl(f'/home/edwardhu/azure/gregyangwu2premblockblob_expoutput/cox_output/depth-block_depth-alpha_1.0')
bigdf_1 = load_all_pkl(f'/home/edwardhu/azure/msrairesidentssa5_expoutput/projects/pilimit/rand-sweep-1.2/pt-results/*')

510

In [26]:
bigdf_1.test_acc.max()

0.6117

In [27]:
bigdf_1.sort_values('test_acc', ascending=False)

,M2,M3,batch_size,bias_alpha,bias_lr_mult,cuda,cycarr,data,depth,epoch,...,scheduler,seed,test_acc,test_batch_size,test_loss,train_acc,train_loss,verbose,wd,width
49,2500200,2500200,8,0.062500,0.5,True,False,./dataset,2,50,...,multistep,1,0.6117,64,1.382816,0.97020,0.145523,False,0.000028,None
44,2250200,2250200,8,0.062500,0.5,True,False,./dataset,2,45,...,multistep,1,0.6113,64,1.385709,0.96636,0.150525,False,0.000028,None
47,2400200,2400200,8,0.062500,0.5,True,False,./dataset,2,48,...,multistep,1,0.6104,64,1.385605,0.96902,0.145679,False,0.000028,None
45,2300200,2300200,8,0.062500,0.5,True,False,./dataset,2,46,...,multistep,1,0.6102,64,1.390089,0.96850,0.147553,False,0.000028,None
48,2450200,2450200,8,0.062500,0.5,True,False,./dataset,2,49,...,multistep,1,0.6097,64,1.382370,0.96984,0.145821,False,0.000028,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,1550200,1550200,8,0.062500,0.5,True,False,./dataset,2,31,...,multistep,1,0.0684,64,43.424350,0.11796,59.888700,False,0.000007,None
0,50200,50200,8,2.000000,0.5,True,False,./dataset,2,1,...,multistep,1,0.0672,64,28.704875,0.11584,25.905548,False,0.000160,None
9,500200,500200,8,2.828427,0.5,True,False,./dataset,2,10,...,multistep,1,0.0637,64,173.182600,0.10670,184.023366,False,0.000226,None
6,350200,350200,8,5.656854,0.5,True,False,./dataset,2,7,...,multistep,1,0.0591,64,510.952000,0.10094,1366.221810,False,0.000160,None
0,50200,50200,8,0.353553,0.5,True,False,./dataset,2,1,...,multistep,1,0.0461,64,140.168000,0.11304,138.722002,False,0.000004,None

In [28]:
bigdf_1.nlargest(5, 'test_acc')[['lr', 'gclip', 'first_layer_lr_mult', 'wd', 'last_layer_lr_mult', 'bias_alpha', 'test_acc']]

,lr,gclip,first_layer_lr_mult,wd,last_layer_lr_mult,bias_alpha,test_acc
49,0.5,0.2,0.282843,0.000028,22.627417,0.0625,0.6117
44,0.5,0.2,0.282843,0.000028,22.627417,0.0625,0.6113
47,0.5,0.2,0.282843,0.000028,22.627417,0.0625,0.6104
45,0.5,0.2,0.282843,0.000028,22.627417,0.0625,0.6102
48,0.5,0.2,0.282843,0.000028,22.627417,0.0625,0.6097